import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Hero } from "@/components/sections";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello, I am Zoe </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Hi there, I am Zoe </h1>
      <nav>
        <li>
          <ul>SUMMARY</ul>
          <ul>SKILLS</ul>
          <ul>GRAPHIC DESIGN PROJECTS</ul>
          <ul>CAREER</ul>
          <ul></ul>
          <ul></ul>
        </li>
      </nav> */}

      <main>
        <Hero />
      </main>
    </>
  )
}
