import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hi, I&apos;m Zoe </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello, I'm Zoe</h1>
      <nav>
        <li>
          <ul>SUMMARY</ul>
          <ul>SKILLS</ul>
          <ul>GRAPHIC DESIGN PROJECTS</ul>
          <ul>CAREER</ul>
          <ul></ul>
          <ul></ul>
        </li>
      </nav>

      <main>
        <div>
          
        </div>
      </main>
    </>
  )
}
